### ISSUE TITLE
link to schemapedia not working

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1105]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/metadata_management

**Describe what you would change to the page**
[Link to schemapedia](https://schemapedia.com) not working, remove or replace (I cannot find any relevant link myself, the ones I find are not particularly informative and link back to the broken one above, which is also listed for sale)

**Comment by bianchini88** [comment]
The same concern obviously applies to the item in the [table](https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668)

**Comment by bedroesb** [comment]
@elixir-europe/rdmkit-editors Hello everyone, schemapedia seems to be offline and unmaintained. The domain name is even for sale. Do we take it out of our content + table?

**Comment by bianchini88** [comment]
Do we have a procedure for this? Should we contact/tag the authors?

**Comment by floradanna** [comment]
We don't really have a procedure, but we do say that the content can be changed by other contributors and that the editors approve or not the suggested changes.

Since this issue is a broken link, I think we could use this issue (or a new one) to describe why we delete "schemapedia" and link the related PR.

What do you think?

**Comment by bianchini88** [comment]
I am not sure... it would be good to have a contact person of some kind for these tools (on FAIRsharing each entry has a "maintainer" attribute). The page might or might not come back, it is difficult to say. I think this is a problem that we will have to face more and more often over time when maintaining the RDMkit.

**Comment by bedroesb** [comment]
This is clearly a broken thing and not a mayor content change, so I would go ahead and fix it...

From what I know, contact persons for a page are actually the editors described in the CONTRIBUTORS file, except for national pages. It are also those people that get tagged when a change is made to the page, not the general contributors. This was discussed not so long ago and we changed the contribute page accordingly: https://rdmkit.elixir-europe.org/how_to_contribute#ownership-of-content

Otherwise RDMkit will quickly become a monolithic block were editors are just tagging 'responsible' people and nothing happens I fear. We have to take the initiative to keep the quality up...

**Comment by bianchini88** [comment]
Fair enough, let's just get rid of it, then. Other plausible links could have been [this](https://www.bibsonomy.org/bibtex/2936b108c7f21da05ed6cfb10fa1c5ef4/maxirichter)
and [this](https://old.datahub.io/dataset/schemapedia) (provided it is the very same schemapedia, which I am not 100% sure of). Both pages are at least 10 years old, and I do not see a point in linking them.
