### ISSUE TITLE
Expandable/Collapsible Menu on Section Headings

### ISSUE THREAD

**Issue by Sherida101** [elixir-europe/rdmkit#1113]
**Description**

Is it possible to have web page content within a collapsible/expandable section heading on the various web pages please?

Example:
	Web page: Bioimaging data
	Web page link: https://rdmkit.elixir-europe.org/bioimaging_data
	Section titles to be in a collapsible/expandable menu: 
		- Related pages
		- More Information
		- Relevant tools and resources
	
	
	
In essence, my suggestion is if all the web pages that have the section headings - "Related pages", "More Information" and "Relevant tools and resources" can be in a collapsible/expandable section.
![biomolecular_simulation_data_web_page_rdmkit](https://user-images.githubusercontent.com/32401854/206425419-c35134c1-7eee-48c7-a60c-0bfcee720403.png)

**Comment by bedroesb** [comment]
Hello @Sherida101, thanks for your feedback! A discussion that we were having was that we users to make better use of the related pages section, because they miss out on it. We don't yet know how we would restyle it, but I had more the use of tiles like we have on the overview pages in mind. The all tools and resources would be collapsed in the new version of RDMkit

**Comment by bedroesb** [comment]
This is finally implemented in #1366. Thanks a lot for the suggestion!

**Comment by Sherida101** [comment]
You're welcome.
