### ISSUE TITLE
New domain page on Single-cell 

### ISSUE THREAD

**Issue by johrollin** [elixir-europe/rdmkit#1348]
**What topic do you wish to add?**
Single-cell sequencing analyses allow the sequencing of individual cells. This information can be used by researchers to identify and understand gene differential behavior between cell.

**Are there existing pages in the RDMkit website related to the requested page?**
No

**Resources**
[Draft ](https://github.com/Developmental-Neuroepigenetics-Lab/rdm_single_cell/blob/master/pages/your_domain/single_cell.md) currently being written/corrected internally at Freiburg university. 

**Context**
as part of the [MeinBio ](https://www.meinbio.uni-freiburg.de/what-is-meinbio-1) project which is mainly focused on single-cell RNAseq and single-cell ATAC. 
The main challenges are related to data saving format and step that are needed for reproducibility.

**Comment by floradanna** [comment]
Hi, thank you for your interest in sharing content in RDMkit!

Your draft appears to be in good shape already. 

We kindly request you to submit a pull request, so that our editors can initiate the review process and provide necessary comments or suggestions in the text directly.

Looking forward to your pull request! 
If you have any questions along the way, don't hesitate to reach out.

**Comment by johrollin** [comment]
We are still making some change, we will submit a pull request hopefully soon.

**Comment by johrollin** [comment]
Hi,
Pull Request submitted for review.
Best
