### ISSUE TITLE
Documentation on how to obtain bibtex entries with Zotero

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1458]
**Description**
Something along these lines should appear in the documentation:
1.  Get https://www.zotero.org/
2. Get better BibTeX https://retorque.re/zotero-better-bibtex/installation/index.html
3.  Use auth.lower + year + shorttitle(1,0) for citation key generation (old entries should be pinned)
4. Get an account
5. Add this group https://www.zotero.org/groups/5371154/rdmkit
6. Add/Import items to zotero (optional to group above)
7. Export as better BibTex and append to references.bib

**Comment by bedroesb** [comment]
I don't know if I like the idea that people have to make an account somewhere in order to contribute something as simple as adding a reference :thinking: Could we describe how we expect the syntax to be in the bibtex file? The bullet list here looks more for when one wants to add bulk submissions. Handy nonetheless, but I just hope it doesn't scare off people!

But maybe this worry is misplaced. We can discuss it in the editorial meeting!

**Comment by bianchini88** [comment]
> Could we describe how we expect the syntax to be in the bibtex file?

I think this is something we should do anyway (for users and editors). As Martin noted, the BibTeX entries obtained with the Zotero method are still not perfect. 

One thing that could be discussed is whether the curation of the bibliography (if necessary) should happen on our BibTeX file on the RDMkit repo or whether we can curate the Zotero collection instead and sync the file on GitHub with the export from Zotero.

> I don't know if I like the idea that people have to make an account somewhere

Agreed. We could give this as an option but not make it compulsory (depending also on how we answer the question above).
