### ISSUE TITLE
An introductory paragraph to the "Your role", "Your Problem" and "Your Domain" section is needed

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#156]
**What topic do you wish to add?**

We needed a space where we can describe the purpose of the "your role" section of the website.

**Are there existing pages in the RDM toolkit website related to the requested page?**

There is the [about page](https://rdm.elixir-europe.org/about.html). But we're not sure if it is the right place for this. 

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

@celiavg and @MijkeJetten  will provide the necessary content

**Comment by bedroesb** [comment]
I will make and link this page

**Comment by DanFaria** [comment]
Do we need an actual page, or would a mouse-over "help" message when you go to "your role" address the problem (if such a thing is even possible using this template)?

**Comment by floradanna** [comment]
I think the current [About page](https://rdm.elixir-europe.org/about.html) is good, since it explain what this RDM toolkit is about (what it is and who it is for etc...).

I agree with the statement that an introduction page is necessary for "your role", but I think that it is also needed for each section ("your domain", "your problem", "tool assembly"). Giving an introduction will clarify the meaning these titles to the readers.

Technically, this can be done by giving to these sections a link in the same way we give a link to the other levels in the main.yaml. However, if we do this, the 4 grey boxes under the RDM cycle image in the [landing page](https://rdm.elixir-europe.org/index.html) will not be able to show the list of sub-pages by unfolding anymore; they will bring you to the "introduction" page of the section directly.
Personally, I would like this solution.
