### ISSUE TITLE
Description heading in Your Problem pages - to be or not to be?

### ISSUE THREAD

**Issue by YvonneKallberg** [elixir-europe/rdmkit#306]
**Describe what you would change to the page**
As it is now some of the Your problem pages has a subheading 'Description' and some do not. I think it would look nicer if all pages had the same heading structure. 

Pages that do: Compliance, DMP, Organisation, Transfer
Pages that don't: Classification, Protection, Publication, Quality, Transfer, Metadata, Storage

**Comment by YvonneKallberg** [comment]
I'm happy to do the changes either way, but which pages should change, the ones _with_ or the ones _without_ a Description subheading? If the heading is to be removed, the template should be changed accordingly.

**Comment by floradanna** [comment]
I suggest to keep "Description", since it is also used in most of Your Domain pages.
I am going to add "Description" very quickly in the following pages: Data Quality, Data Transfer, Metadata.

The other 3 pages in which "Description" needs to be added are: Classification, Protection and Storage. However, here it is more complicated because there a lack of description in addition to the lack of the heading. So, I will not be able to fix these pages.

**Comment by jmenglund** [comment]
I added a description for the problem "Is my data sensitive?" on the data classification page. See PR #363

**Comment by pinarpink** [comment]
We also changed the Data Protection page so that it has the "description" heading.
