### ISSUE TITLE
Gap analysis for remaining pages (post Jan2021 contentathon)

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#364]
**Description**
Pages for which gap analysis has not been done yet:

- [ ] Storage
- [ ] Data classification
- [ ] ...

**Comment by jmenglund** [comment]
I just made a PR (#362) with some updates to Data classification. There might still be things left to do, though...

**Comment by floradanna** [comment]
- [ ] Almost all "Your Problem" pages need a revision.
- [ ] Identified missing pages/topics:
* FAIR principles and definition of DATA in this RDMkit
* Archiving, Cold vs Active storage
* Informed consent
* Cloud 
* Collaborative research
* Federated computing
* Data Documentation
* File format open vs proprietary

**Comment by jmenglund** [comment]
I think it would also make sense to write somewhere about the Nagoya protocol and EUs ABS (Access and Benefit Sharing) legislation, https://ec.europa.eu/environment/nature/biodiversity/international/abs/

**Comment by veraort** [comment]
> I think it would also make sense to write somewhere about the Nagoya protocol and EUs ABS (Access and Benefit Sharing) legislation, https://ec.europa.eu/environment/nature/biodiversity/international/abs/

I organized a Nagoya Information meeting in Germany a few years ago. I have some content I could add if we want to build a page on this topic.

**Comment by jmenglund** [comment]
That's great @veraort that you want to contribute on this in my mind very important issue! I'm also happy to contribute some content if people think it a good idea to include the information on the site.

After giving it some thoughts during the weekend, my suggestions would for the moment be to add a separate problem page called "Access and benefit-sharing (ABS)" with a problem called something like "Is access and benefit-sharing (ABS) legislation relevant for my research?"

What do you think @floradanna @veraort?

**Comment by veraort** [comment]
> That's great @veraort that you want to contribute on this in my mind very important issue! I'm also happy to contribute some content if people think it a good idea to include the information on the site.
> 
> After giving it some thoughts during the weekend, my suggestions would for the moment be to add a separate problem page called "Access and benefit-sharing (ABS)" with a problem called something like "Is access and benefit-sharing (ABS) legislation relevant for my research?"
> 
> What do you think @floradanna @veraort?

I like the idea and the working title

**Comment by floradanna** [comment]
It sounds interesting. We have to see what is the best place for this topic in the RDMKit, indeed.
I am not familiar with Nagoya protocol and ABS, is it something valid for Biological Diversity only or it applies to every domain?
Is it about sharing data with the World Wide Web and society (so, publishing data)?

**Comment by jmenglund** [comment]
The Nagoya protocol is a supplementary agreement to  Convention on Biological Diversity (CBD). Its main purpose is to ensure fair and equitable sharing of benefits arising from utilisation of genetic resources and from traditional knowledge assoociated with genetic resources. Many contries, as well as the EU, are parties of the Nagoya protocol.

In order to *access* a genetic resource from a provider country that have some kind of ABS legislation in place, you must first have a prior informed consent (PIC). In order to *use* the resource, you must additionally negotiate an agreement (often referred to as Mutually Agreed Terms, MAT) on how to share resulting benefits.

## Why should we include ABS in the RDMKit? 

I can see the following reasons why we should write about ABS in the RDMKit:

* Data about genetic resources are tightly connected to the genetic resources they are derived from. In order to use data from a resource properly, you must be aware of any restrictions (if there are any) concerning the access of that resource.
* ABS regulations put high demands on documentation. This needs to be taken into account when planning a research project. When negotiating the Mutually Agreed Terms, it is very important to also think about the future reusability of the data. If ABS is relevant to the project, I would argue that it should be part of the data management plan.
* When sharing data, it is important to include necessary metadata regarding ABS in order to make reuse of the data possible. Unfortunately, there is no standardised way of sharing the information that I am aware of.

**Comment by floradanna** [comment]
Could this topic be a sub-problem in the [Compliance and Monitoring](https://rdm.elixir-europe.org/compliance_monitoring.html) page, in your problem section?

@pinarpink What do you think?

**Comment by jmenglund** [comment]
I would be fine with having it as a sub-problem in the Compliance and Monitoring page. We can always move it to a separate page later if that feels better.

**Comment by veraort** [comment]
> The Nagoya protocol is a supplementary agreement to Convention on Biological Diversity (CBD). Its main purpose is to ensure fair and equitable sharing of benefits arising from utilisation of genetic resources and from traditional knowledge associated with genetic resources. Many contries, as well as the EU, are parties of the Nagoya protocol.
> 
> In order to _access_ a genetic resource from a provider country that have some kind of ABS legislation in place, you must first have a prior informed consent (PIC). In order to _use_ the resource, you must additionally negotiate an agreement (often referred to as Mutually Agreed Terms, MAT) on how to share resulting benefits.
> 
> ## Why should we include ABS in the RDMKit?
> I can see the following reasons why we should write about ABS in the RDMKit:
> 
> * Data about genetic resources are tightly connected to the genetic resources they are derived from. In order to use data from a resource properly, you must be aware of any restrictions (if there are any) concerning the access of that resource.
> * ABS regulations put high demands on documentation. This needs to be taken into account when planning a research project. When negotiating the Mutually Agreed Terms, it is very important to think about the future reusability of the data. If ABS is relevant to the project, I would argue that it should be part of the data management plan.
> * When sharing data, it is important to include necessary metadata regarding ABS in order to make reuse of the data possible. Unfortunately, there is no standardised way of sharing the information that I am aware of.
> 
> ABS is not relevant for all genetic resources. It applies only to resources that have been accessed from a provider country after October 12, 2014. Some genetic resources are explicitly excluded, like for example human genomes, some crops and some viruses. To complicate things further, there are also countries that are party of the Nagoya protocol, but have no ABS legislation in place (like my own country Sweden).

This is already a great starting point and much much more than a summary. How we would continue? I would suggest moving this topic, because we are at a point past "gap analysis"?

**Comment by floradanna** [comment]
Since you already have quite some content, I suggest you open an issue + a draft pull request to edit the Compliance Monitoring page, so that you can start adding the content according to the page template (description of the problem, considerations, solutions).
