### ISSUE TITLE
Your Role pages need update

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#374]
Content of the your role pages is merged to have more accurate screenshots.

TODO:
- [x] Decide on the new tag for data steward infrastructure
- [x] Retagging the pages with the new tags to generate the relevant topics list
- [x] Place keywords correctly

**Comment by floradanna** [comment]
During the last editorial meeting, it was decided to keep the current tags, even though they don't match exactly the names of the pages, because the names of the pages are too long to be used as tag.
- [ ] Decide on the new tag for data steward infrastructure: we keep the current tags
- [ ] Retagging the pages with the new tags to generate the relevant topics list &
- [ ] Retagging the tools: No need to do that. There is a clear and correct relation between your ROLE PAGES and CURRENT TAGS
  * Researcher = researcher
  * Data steward policy = policy officer
  * Data steward research = data manager
  * Data steward infrastructure = IT support

- [ ] Place keywords correctly

**Comment by bedroesb** [comment]
These problems re taken care off in PR #414
