### ISSUE TITLE
Editorial board section

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#380]
- Who are the people in the editorial board 
- What do editors do? responsibilities
- How can you contact them
- How can you join?

**Comment by floradanna** [comment]
How to apply to become an editor. Apply by writing a motivation letter, what area you are interested in, list experience.
In both About page (above carousel), Contribute page.

**Comment by floradanna** [comment]
@CaroleGoble @frederikcoppens  I made a first draft. Please, edit it further. I will then make it into a PR.

**Join as Editorial Board Member**
Being on the editorial board of RDMKit means shaping the way RDM best practices, written by experts, are communicated to the readers who are interested in applying those best practices in their everyday work.

**Advantages of being an RDMkit editor**
- You will keep yourself up-to-date with numerous RDM topics while checking and suggesting the changes in proposed content.
- This work helps to increase your visibility as expert in RDM.
- You will suggest thematic gaps that should be added to the RDMkit.
- You will expand your professional network.
- You will make an impact in improving RDM in Life Sciences by using effective way to communicate best practices to stakeholders.

**Responsibilities**
1. Careful consideration and examination of topics proposed by contributors, to make sure that is relevant for the RDMkit.
2. Work together with contributors to find what is the appropriate section in RDMkit for a specific content.
3. Provide timely feedback for improving the quality of the content, according to RDMkit style guide.
4. Formatting content according to RDMkit templates.
5. Manage a Github repository.

**Call for joining us**
RDMkit is receiving lot of attention from policy makers, funders and RDM infrastructure providers, therefore editorial board members should be professionals and experts in RDM, with an interest for effective digital communication, who can help in keeping high quality content.
Requirements:
1.    The applicant must have experience in RDM.
2.    The applicant must be interested in effective digital communication of best practices and guidelines.
3.    The applicant should be willing to spend some time on evaluation of content.
4.  The applicant should be open to discuss topics with other editorial board members and to accept feedback.
5. The applicant should have basic knowledge of Github.

**Application**
To apply for this position, please provide:
- A short motivation letter (a couple of paragraphs) describing why you would like to join the RDMkit editorial board.
- A summary of your experience in RDM.
- List of the RDMkit sections that you most interested in.

Please, send your application to rdm-editors@elixir-europe.org.

**Comment by CaroleGoble** [comment]
Its a really good start. I would do a bit of wordsmithing tomorrow during the EOSC-Life AGM - too tired now!

**Comment by frederikcoppens** [comment]
Some suggestions for changes. I guess it's easier to put something online and then tweak that, rather than in these comments ? Most important changes are in bold

Join as Editorial Board Member

Being on the editorial board of RDMkit entails shaping how RDM best practices, written by experts, are communicated to the readers who are interested in applying those best practices in their everyday work. **As an editor you contribute to the vision of how this information is presented to the life science community at large.**

Advantages of being an RDMkit editor

You will be up-to-date with numerous RDM topics while reviewing proposed content.
This work helps to increase your visibility as expert in RDM.
You will be able to suggest thematic gaps that should be added to the RDMkit, **of which you can take ownership as part of the team.**
You will expand your professional network.
You will make an impact in improving RDM in Life Sciences by developing effective ways to communicate best practices to stakeholders.

Responsibilities

Careful consideration and examination of topics proposed by contributors, to make sure it is relevant for the RDMkit.
Work together with contributors how and where their specific contribution fits best in RDMkit.
Provide timely feedback for improving the quality of the content, according to the RDMkit style guide.
Formatting content according to RDMkit templates.
**Join the biweekly editorial meeting.**
Manage a Github repository.

Call for joining us

RDMkit is receiving lot of attention from policy makers, funders and RDM infrastructure providers, therefore editorial board members should be professionals and experts in RDM, with an interest for effective digital communication, who can help in keeping high quality content.
**We want to keep the editorial board manageable in numbers, therefore we are looking for complementary expertise to the current members.** 

Requirements

The applicant must have experience in RDM.
The applicant must be interested in effective digital communication of best practices and guidelines.
The applicant should be willing to spend some time on evaluation of content.
The applicant should be open to discuss topics with other editorial board members and to accept feedback.
The applicant should have basic knowledge of Github.

Application

To become part of the editorial team, please provide:

A short motivation letter (a couple of paragraphs) describing why you would like to join the RDMkit editorial board.
A summary of your experience in RDM.
List of the RDMkit sections that you are most interested in (or feel are missing).

**Comment by CaroleGoble** [comment]
Looks good!

Carole




========================================
Professor Carole Goble CBE FREng FBCS CITP
Kilburn Building, Department of Computer Science, The University of Manchester,
Oxford Road, Manchester, M13 9PL, UK
email: ***@***.******@***.***>, twitter: @CaroleAnneGoble

**Comment by frederikcoppens** [comment]
Should we link to a list of the current editors ? With also their institutes (to give some visibility)

**Comment by bedroesb** [comment]
@frederikcoppens I am working on the panels at this very moment: https://rdmkit.elixir-europe.org/editorial_board.html
Does this mean that people can give there institute/country as a metadata field to the contributors? 
https://github.com/elixir-europe/rdmkit/blob/master/_data/CONTRIBUTORS.yaml

**Comment by frederikcoppens** [comment]
we then probably want the logos of the institutes, so will be a bit more manual. Let me get back to you on this. Thanks for the link to the page already

**Comment by bedroesb** [comment]
@frederikcoppens I tried things with logo's but that fact that the sizes and colors differentiate so much between institutes did not make it look nice when small ... What would you think about an affiliation text field like in #497 

![Screenshot from 2021-04-01 20-26-27](https://user-images.githubusercontent.com/44875756/113338598-9ce30d00-9329-11eb-9882-05899e3ae237.png)
![Screenshot from 2021-04-01 20-26-55](https://user-images.githubusercontent.com/44875756/113338602-9d7ba380-9329-11eb-81f5-1eda3e38273e.png)

**Comment by bedroesb** [comment]
@frederikcoppens I opened a new issue concerning this #499
