### ISSUE TITLE
Add "Is access and benefit-sharing (ABS) legislation relevant for my research?" to Your Problem – Compliance Monitoring

### ISSUE THREAD

**Issue by jmenglund** [elixir-europe/rdmkit#382]
**Link to the page of interest**
https://rdm.elixir-europe.org/compliance_monitoring.html

**Describe what you would change to the page**
Based on discussions in issue #364, I would like to add a problem concerning access and benefit-sharing (ABS).

**Comment by floradanna** [comment]
Thanks for opening this issue.

Would it be possible to highlight in the title what is the problem that ABS could solve, instead of saying that ABS is a solution for some problems?
For instance maybe: "How can you access genetic resources of a country?". Or some similar kind of question.

Please, let me know if my example is not clear enough.

**Comment by jmenglund** [comment]
Yes, that is a good point! What do you think about something like "How can I ethically access genetic resources of another country?". I would prefer to narrow it down to ethical aspects, so that we don't have to write about other problems involved in getting access to resources.

**Comment by floradanna** [comment]
Yes, it sounds good to me. Thank you.
