### ISSUE TITLE
New page - Structural Bioinformatics

### ISSUE THREAD

**Issue by bordin89** [elixir-europe/rdmkit#450]
**What topic do you wish to add?**
We wish to add a page for the domain of Structural Bioinformatics and the associated tag in the yml file (https://github.com/elixir-europe/rdmkit/blob/master/_data/tags.yml) to be generated;

**Are there existing pages in the RDMKit website related to the requested page?**

This will be added to the 'your domain' section of RDMKit

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by bedroesb** [comment]
Hello @bordin89 

A page is created at: https://rdmkit.elixir-europe.org/structural_bioinformatics together with the tag `struct bioinfo`

In order to add your content, first click on the link and click on edit me, and then on the "pencil icon" on the GitHub page, as describe in our ["Contribute guide"](https://rdm.elixir-europe.org/github_way.html#write-your-content-and-make-a-pull-request). You can save your draft as "Draft Pull Request" until the content is ready for review, as described in the guide.

Let me know if you have any questions. Thanks!

**Comment by bordin89** [comment]
Hi @bedroesb,

Thanks! We're working on it and we'll start populating that page soon once it's finished. Thanks for setting this up!
