### ISSUE TITLE
Content link missing ?

### ISSUE THREAD

**Issue by cpommier** [elixir-europe/rdmkit#613]
Quick feedback for the navigability of this very good site. 
When I was in the contribute pages I felt a bit stuck and understanding that I had to click on the RDMKit logo to go back to the home page was not obvious. 
I managed without any problem of course,  but it could get confusing for some visitors. Adding a « Content » header next to "About" could do the trick. But it could be a bad idea.
If you don’t think that’s a good suggestion, no problem.

**Comment by bedroesb** [comment]
The original idea was to use breadcrumbs, but since we have only two levels of pages that might not be needed. We could also put a button on top of the sidebar to go back to the main content

**Comment by martin-nc** [comment]
I think a home page link would be a good idea. It's not always obvious to people that clicking on a logo might take them back to the home page. I think this would help connect the 'About' section to the rest of the site, so you can jump more easily between them. Here's a suggestion: in the top menu, remove the 'Give feedback' link and add a 'Home' link at the start of the links (before 'About').

I'm not sure the 'Give feedback' link is useful because:
1. We have the contact address sprinkled across the site and there is a 'Contact' link in the footer. People can also use GitHub to suggest anything.
2. The link does not disclose the email address. I think this is a bad thing because it immediately tries to open the native email client on someone's device, and many people (like me!) don't use the native email client. They might use another client, or webmail. In this case they just want an email address. So clicking the link simply opens a program you don't want to open! 

@bedroesb I hadn't really noticed this before! Maybe we should change the footer contact link to an email address as well, which can still be a `mailto:` link, but which gives people the option to copy and paste it if they want. Either that, or we link it to a contact form.
