### ISSUE TITLE
deposition tools on storage page

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#695]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/storage.html

**Describe what you would change to the page**
some of the tools are not for storage, but for deposition e.g. dataverse

**Comment by floradanna** [comment]
I don't know enough to decide what's storage and what's data deposition.

Dataverse was added because some institutes host a local instance that is used to store and share data (in a controlled way). See the text in the storage page:

![Screenshot 2021-09-07 at 11 34 58](https://user-images.githubusercontent.com/51486716/132322620-fd78dc29-617a-454c-b568-1d7eeac424f0.png)

And the text in IFB assembly:

![Screenshot 2021-09-07 at 11 34 32](https://user-images.githubusercontent.com/51486716/132322696-9c3e37da-cf77-4fd4-88d0-43feb1a31b3c.png)

If Dataverse is not storage, please feel free to make a PR to change the text in each page. I can take care of deleting the tag from the excel spreadsheet for tools.

**Comment by korbinib** [comment]
Thank you for sharing the considerations.
I am not sure if storage and deposition/archival can be completely separated. In any case  the tool seems to be more suited for static content, hence the comment.
