### ISSUE TITLE
Human data VS Health data

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#753]
**Description**
- Some tools and resources for evaluating the data quality of health data are currently in "Data quality" task page.
- Is the "Human data" domain page focus only on Genomics/Omics/Molecular data? If yes, could it be worth it to think about re-naming the page to clarify that?
- Shall we agree on a definition to distinguish what we mean with "Human VS Health data"?
- Could COVID related information go to the Human AND/OR Health page?

**Comment by lauportell** [comment]
The human data page is not only focused in omics data, it also includes health data information specially when it talks about GA4GH. I would say we can add a sentence in the human data page pointing to the resources on the Data Quality page for health data, because it is important information realated to human data but we don't want to duplicate info in the pages.

We could think of dividing the human data page into omics data and health data, so that we can relate the resources we have to one of these two aspects, including COVID information. Do you think this would be feasable or might be confusing for the users?

**Comment by lauportell** [comment]
The health data focus group is working on a separate page for health data.

**Comment by bedroesb** [comment]
@lauportell we now have a separate health data page, do we need this issue?

**Comment by lauportell** [comment]
yes, we can close it!

**Comment by bedroesb** [comment]
Woop woop!
