### ISSUE TITLE
Suggestion to replace titles for 'Data Life Cycle' pages

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/rdmkit#774]
Currently, for each 'Data Life Cycle' page, heading/title is written in a form of "-ing" noun e.g. Planning, Preserving, etc. 

This can be difficult to understand especially for website visitors that need screen reader to access page content.

It would be better to rename title, for example: Data Collection, Data Preservation, Data Reuse, etc - and, I think it's fine for titles to be a little different/inconsistent to help make content more clear, e.g. for first step: Plan, page title can be Data Management Planning instead of Data Planning.

Happy to know your thoughts! Thank you.

**Comment by lauportell** [comment]
Hi @bedroesb can we make this changes? We were discussing in the editorial meeting that we would like to change it but we need to first check that it doesn't mess with tags.

**Comment by bedroesb** [comment]
The titles can be changed without a problem, but I am concerned that is will become confusing with the your task pages. There we already have data analysis, data management plan etc...

**Comment by lauportell** [comment]
then maybe we should discuss it further

**Comment by korbinib** [comment]
The connected task page could be named as such. E.g.: "Tasks in data management planning" - however I think this possibly would only move the accessibility issue to a different place.

**Comment by bedroesb** [comment]
tasks are used as tags for the tools, so I would keep those titles short :)

**Comment by martin-nc** [comment]
One option might be to have a mini title to show the section the page is in: 

<img width="966" alt="Screenshot 2022-01-20 at 18 15 45" src="https://user-images.githubusercontent.com/15261745/150397809-fc68f33a-6126-422b-9db1-1a0eaba3896c.png"  >

This can be within the `<h1>` (the code is a bit clunky!): 

`<h1><span>Data life cycle</span><span class="hidden">:</span> Planning</h1>`

 so for screen readers it would read "Heading one, data life cycle colon planning", which might be okay. BUT this might mess things up for Bert if the `<h1>` simply prints out the title from the front matter. Alternatively use an Aria role:
```
<div role="doc-subtitle">Data life cycle</div>
<h1>Planning</h1>
```

It's cleaner but I'm not sure it's as robust. The recommendation is to use the actual heading tag rather than `role`, but it might be the best compromise for us. Of course then we'd need to extend this to the other sections as well, but maybe that's useful, especially when you lose the side menu context on small screens?

Anyway, just an idea.

**Comment by Nazeeefa** [comment]
Thank you for this idea @martin-nc, I appreciate your time.
Let's implement this :)

**Comment by bedroesb** [comment]
![Screenshot from 2022-01-21 14-44-04](https://user-images.githubusercontent.com/44875756/150537298-a7f53ec5-0693-4882-b667-0d0ec58e48e2.png)
![Screenshot from 2022-01-21 14-43-48](https://user-images.githubusercontent.com/44875756/150537304-8018c174-40a8-4959-bfc9-91be5865b786.png)
![Screenshot from 2022-01-21 14-43-05](https://user-images.githubusercontent.com/44875756/150537308-07bdf301-91d3-4ef8-9beb-c59c08828fca.png)

These are some examples with the font weight. I think if we make it bold, it is to similar with the subheadings

**Comment by bedroesb** [comment]
An even better possibility: Gray
![Screenshot from 2022-01-21 15-19-36](https://user-images.githubusercontent.com/44875756/150542565-f635ffdb-8960-43b9-be5e-eecd61f29c19.png)

**Comment by martin-nc** [comment]
Yes, I prefer the grey one. The red ones stand out a little too much.
